#!/bin/bash
################################################################################
# Hermes Remote Control - Envia comandos do WSL para Mac M1 via GitHub
################################################################################

set -e

REPO_NAME="hermes-mac-tasks"
GITHUB_USER="lucasdoreac"

# Cores
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

usage() {
    cat << EOF
Uso: $0 [comando] [argumentos]

Comandos disponíveis:
  setup           Cria repositório de tarefas no GitHub
  send <cmd>      Envia comando para o Mac
  status          Verifica status do Mac
  logs            Busca logs do Mac
  exec <cmd>      Execução direta via GitHub Actions

Exemplos:
  $0 setup
  $0 send "hermes --version"
  $0 exec "brew list"

EOF
    exit 1
}

################################################################################
# Criar repositório de tarefas
################################################################################

setup_repo() {
    echo -e "${GREEN}[INFO]${NC} Criando repositório $REPO_NAME..."

    # Criar repo
    gh repo create "$REPO_NAME" --public --description "Hermes Mac M1 Remote Tasks"

    # Clonar
    cd /tmp
    rm -rf "$REPO_NAME"
    gh repo clone "$GITHUB_USER/$REPO_NAME"

    cd "$REPO_NAME"

    # Criar README
    cat > README.md << 'EOF'
# Hermes Mac M1 Remote Tasks

Repositório para controle remoto do Mac M1 via GitHub CLI.

## Como funciona

1. O Mac poll este repositório a cada 60 segundos
2. Quando um arquivo `task.sh` aparece, o Mac executa
3. O resultado é salvo em `logs/` e o task é removido

## Enviar comando

No WSL:
```bash
cd /tmp/hermes-mac-tasks
cat > task.sh << 'SCRIPT'
#!/bin/bash
# Seu comando aqui
hermes --version
SCRIPT

git add task.sh
git commit -m "Task: <descrição>"
git push origin main
```

## Ver resultado

```bash
git pull
cat logs/task-*.log
```
EOF

    git add README.md
    git commit -m "Initial commit"
    git push origin main

    echo -e "${GREEN}[INFO]${NC} Repositório criado: https://github.com/$GITHUB_USER/$REPO_NAME"

    # Criar diretório de logs
    mkdir -p logs
    git add logs
    git commit -m "Add logs directory"
    git push

    echo -e "${GREEN}[SUCCESS]${NC} Setup completo! Agora execute o setup no Mac."
}

################################################################################
# Enviar comando para o Mac
################################################################################

send_command() {
    local cmd="$1"

    echo -e "${GREEN}[INFO]${NC} Enviando comando para o Mac..."
    echo -e "${YELLOW}[CMD]${NC} $cmd"

    cd "/tmp/$REPO_NAME" || {
        echo -e "${RED}[ERROR]${NC} Repositório não encontrado. Execute 'setup' primeiro."
        exit 1
    }

    # Criar task
    cat > task.sh << EOF
#!/bin/bash
# Generated by Hermes Remote Control
# Date: $(date)

$cmd

exit_code=\$?
echo "Exit code: \$exit_code"
exit \$exit_code
EOF

    chmod +x task.sh

    # Commit e push
    git add task.sh
    git commit -m "Task: $cmd"
    git push origin main

    echo -e "${GREEN}[SUCCESS]${NC} Comando enviado! O Mac executará em até 60 segundos."
}

################################################################################
# Ver status do Mac
################################################################################

check_status() {
    echo -e "${GREEN}[INFO]${NC} Verificando status do Mac..."

    cd "/tmp/$REPO_NAME" || {
        echo -e "${RED}[ERROR]${NC} Repositório não encontrado."
        exit 1
    }

    git pull origin main

    if [[ -f "task.sh" ]]; then
        echo -e "${YELLOW}[STATUS]${NC} Task pendente encontrada"
        cat task.sh
    else
        echo -e "${GREEN}[STATUS]${NC} Nenhum task pendente"
    fi

    if ls logs/*.log 1> /dev/null 2>&1; then
        echo -e "${GREEN}[INFO]${NC} Logs disponíveis:"
        ls -lt logs/*.log | head -5
    else
        echo -e "${YELLOW}[INFO]${NC} Nenhum log disponível"
    fi
}

################################################################################
# Buscar logs do Mac
################################################################################

get_logs() {
    echo -e "${GREEN}[INFO]${NC} Buscando logs do Mac..."

    cd "/tmp/$REPO_NAME" || {
        echo -e "${RED}[ERROR]${NC} Repositório não encontrado."
        exit 1
    }

    git pull origin main

    if ls logs/*.log 1> /dev/null 2>&1; then
        echo -e "${GREEN}[INFO]${NC} Últimos logs:"
        tail -50 "$(ls -t logs/*.log | head -1)"
    else
        echo -e "${YELLOW}[INFO]${NC} Nenhum log disponível"
    fi
}

################################################################################
# Execução direta via GitHub Actions
################################################################################

exec_direct() {
    local cmd="$1"

    echo -e "${GREEN}[INFO]${NC} Executando comando via GitHub Actions..."

    # Criar workflow
    mkdir -p .github/workflows

    cat > .github/workflows/remote-cmd.yml << EOF
name: Remote Command

on:
  workflow_dispatch:

jobs:
  execute:
    runs-on: macos-latest
    steps:
      - name: Execute command
        run: |
          $cmd
EOF

    cd "/tmp/$REPO_NAME" || {
        echo -e "${RED}[ERROR]${NC} Repositório não encontrado."
        exit 1
    }

    git add .github/workflows/remote-cmd.yml
    git commit -m "Add remote command workflow"
    git push origin main

    # Trigger workflow
    gh workflow run remote-cmd.yml

    echo -e "${GREEN}[SUCCESS]${NC} Workflow disparado! Acompanhe em:"
    echo "https://github.com/$GITHUB_USER/$REPO_NAME/actions"
}

################################################################################
# Main
################################################################################

case "${1:-}" in
    setup)
        setup_repo
        ;;
    send)
        if [[ -z "${2:-}" ]]; then
            echo -e "${RED}[ERROR]${NC} Especifique o comando"
            usage
        fi
        send_command "$2"
        ;;
    status)
        check_status
        ;;
    logs)
        get_logs
        ;;
    exec)
        if [[ -z "${2:-}" ]]; then
            echo -e "${RED}[ERROR]${NC} Especifique o comando"
            usage
        fi
        exec_direct "$2"
        ;;
    *)
        usage
        ;;
esac
